#!/usr/bin/env ksh

bspc monitor HDMI-A-0 -d "" "" "" "" ""
bspc monitor HDMI-A-1 -d "" "" "" "" ""

bspc config border_width			4
bspc config window_gap				10

bspc config split_ratio				0.5
bspc config single_monocle			false
bspc config focus_follows_pointer	true
bspc config borderless_monocle		true
bspc config gapless_monocle			true

bspc config focused_border_color	"#BD93F9"
bspc config normal_border_color		"$BACKGROUND"
bspc config active_border_color		"$MAGENTA"
bspc config presel_feedback_color	"$GREEN"

dunst &
feh --bg-fill ~/Pictures/Wallpapers/solarized_puffy.png &
sxhkd &
xsetroot -cursor_name left_ptr
xset r rate 200 50
