#!/bin/bash

# Simple Make Script
# This, well makes scripts what more do you want me to say?

if [ -n "$1" ] && (( $# < 2 )); then
	touch "$1"
	chmod +x "$1"
	vim "$1"
fi

if [ -z "$1" ]; then
	printf "Enter the name of the file, you mongoloid \n"
fi

