#!/bin/bash

TIME=$(shuf -i 1800-10800 -n 1)s
# COW=$(find /usr/share/cows/ -iname "*.cow" | shuf -n 1 | awk -F / '{print $NF}')

VAR2="0"

while :; do
	VAR1=$(shuf -n 1 ~/.scripts/insults.txt | cowsay -f sodomized)
	if [ "$VAR1" != "$VAR2" ]
	then
		notify-send -t 7500 "$VAR1"
		VAR2="$VAR1"
		sleep "$TIME"
	fi
done
